[pytest]
addopts = -v --tb=short
markers =
    # Đánh dấu các test là smoke tests
    smoke: smoke tests 
    # Đánh dấu các test là UI tests
    ui: UI tests 
    # Đánh dấu các test là API tests
    api: API tests  
    # Đánh dấu các test là regression tests
    regression: regression tests 
